CREATE OR REPLACE PROCEDURE asignar_tecnicos AS
    tecnico_id NUMBER;
    orden_id NUMBER;
BEGIN
    FOR registro IN (
        SELECT ao.ORDER_ID, ao.DAMAGE_ID, ao.CUSTOMER_ID, ao.REPORT_DATE, d.PRIORITY AS DAMAGE_PRIORITY, c.TYPE AS CUSTOMER_TYPE,
               (SYSDATE - ao.REPORT_DATE) AS DIAS_REPORTE
        FROM APP_ATEN_DANOS.ATTENTION_ORDER ao
        JOIN APP_ATEN_DANOS.DAMAGE d ON ao.DAMAGE_ID = d.DAMAGE_ID
        JOIN APP_ATEN_DANOS.CUSTOMER c ON ao.CUSTOMER_ID = c.CUSTOMER_ID
        WHERE ao.TECHNICIAN_ID IS NULL AND ao.FIXED_DATE IS NULL
        ORDER BY d.PRIORITY DESC, c.TYPE DESC, ao.REPORT_DATE ASC
        FETCH FIRST 10 ROWS ONLY
    ) LOOP

        
        SELECT ts.TECHNICIAN_ID INTO tecnico_id
        FROM APP_ATEN_DANOS.TECHNICIAN_SPECIALTY ts
        WHERE ts.DAMAGE_ID = registro.DAMAGE_ID
        AND ROWNUM = 1;

        
        UPDATE APP_ATEN_DANOS.ATTENTION_ORDER
        SET TECHNICIAN_ID = tecnico_id
        WHERE ORDER_ID = registro.ORDER_ID;

    END LOOP;
END;
/
