CREATE OR REPLACE TRIGGER APP_ATEN_DANOS.TRG_SET_FIXED_DATE
BEFORE UPDATE OF DURATION ON APP_ATEN_DANOS.ATTENTION_ORDER
FOR EACH ROW
WHEN (NEW.DURATION IS NOT NULL AND OLD.FIXED_DATE IS NULL)
BEGIN
    :NEW.FIXED_DATE := SYSDATE;
END;
/
