server:
  port: 8080  

spring:
  application:
    name: API-GATEWAY 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true 
      routes:
        - id: USER-MANAGEMENT 
          uri: lb://USER-MANAGEMENT 
          predicates:
            - Path=/api/user-management/**

        - id: DAMAGE-ORDER  # ID for the new microservice
          uri: lb://DAMAGE-ORDER  # Load balanced URI
          predicates:
            - Path=/api/damage-order/**  # Ruta para el nuevo microservicio
    
        - id: SCHEDULING-SERVICE  
          uri: lb://SCHEDULING-SERVICE
          predicates:
            - Path=/api/scheduling-service/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true  # Registra el API Gateway con Eureka
    fetchRegistry: true  # Habilita la búsqueda del registro de Eureka para descubrir servicios
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # URL del registro de Eureka
