BEGIN 
    -- Asumiendo que los daños se reportan en días diferentes para simplificar
    INSERT INTO APP_ATEN_DANOS.ATTENTION_ORDER(ORDER_ID, ORDER_DESCRIPTION, CUSTOMER_ID, DAMAGE_ID, TECHNICIAN_ID, REPORT_DATE)
    VALUES (1, 'Revisión de cableado', 3, 1, 1, TRUNC(SYSDATE));

    INSERT INTO APP_ATEN_DANOS.ATTENTION_ORDER(ORDER_ID, ORDER_DESCRIPTION, CUSTOMER_ID, DAMAGE_ID, TECHNICIAN_ID, REPORT_DATE)
    VALUES (2, 'Falla en la conexión a internet', 4, 2, 2, TRUNC(SYSDATE) - 1);

    INSERT INTO APP_ATEN_DANOS.ATTENTION_ORDER(ORDER_ID, ORDER_DESCRIPTION, CUSTOMER_ID, DAMAGE_ID, TECHNICIAN_ID, REPORT_DATE)
    VALUES (3, 'Corte de servicio', 5, 3, 3, TRUNC(SYSDATE) - 2);

    INSERT INTO APP_ATEN_DANOS.ATTENTION_ORDER(ORDER_ID, ORDER_DESCRIPTION, CUSTOMER_ID, DAMAGE_ID, TECHNICIAN_ID, REPORT_DATE)
    VALUES (4, 'Problemas con el router', 6, 4, 4, TRUNC(SYSDATE) - 3);

    INSERT INTO APP_ATEN_DANOS.ATTENTION_ORDER(ORDER_ID, ORDER_DESCRIPTION, CUSTOMER_ID, DAMAGE_ID, TECHNICIAN_ID, REPORT_DATE)
    VALUES (5, 'Mantenimiento preventivo', 7, 5, 5, TRUNC(SYSDATE) - 4);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        raise_application_error(-20000, SQLCODE || '=>' || SQLERRM, TRUE);   
END;
