-- DROP USER APP_ATEN_DANOS;

CREATE USER APP_ATEN_DANOS
-- IDENTIFIED BY <password>
;

CREATE TABLE "APP_ATEN_DANOS"."ATTENTION_ORDER" 
   (	"ORDER_DESCRIPTION" VARCHAR2(200), 
	"REPORT_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DAMAGE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"TECHNICIAN_ID" NUMBER(10,0), 
	"DURATION" INTERVAL DAY (2) TO SECOND (6), 
	"FIXED_DATE" DATE, 
	"ORDER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "APP_ATEN_DANOS"."ATTENTION_ORDER_PK" ON "APP_ATEN_DANOS"."ATTENTION_ORDER" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
ALTER TABLE "APP_ATEN_DANOS"."ATTENTION_ORDER" ADD CONSTRAINT "ATTENTION_ORDER_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX "APP_ATEN_DANOS"."ATTENTION_ORDER_PK"  ENABLE;

ALTER TABLE "APP_ATEN_DANOS"."ATTENTION_ORDER" ADD CONSTRAINT "FK_ATTENTION_ORDER_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "APP_ATEN_DANOS"."CUSTOMER" ("CUSTOMER_ID") ENABLE;
  ALTER TABLE "APP_ATEN_DANOS"."ATTENTION_ORDER" ADD CONSTRAINT "FK_ATTENTION_ORDER_DAMAGE" FOREIGN KEY ("DAMAGE_ID")
	  REFERENCES "APP_ATEN_DANOS"."DAMAGE" ("DAMAGE_ID") ENABLE;
  ALTER TABLE "APP_ATEN_DANOS"."ATTENTION_ORDER" ADD CONSTRAINT "FK_ATTENTION_ORDER_TECHNICIAN" FOREIGN KEY ("TECHNICIAN_ID")
	  REFERENCES "APP_ATEN_DANOS"."TECHNICIAN" ("TECHNICIAN_ID") ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "APP_ATEN_DANOS"."TRG_SET_FIXED_DATE" 
BEFORE UPDATE OF DURATION ON APP_ATEN_DANOS.ATTENTION_ORDER
FOR EACH ROW
 WHEN (NEW.DURATION IS NOT NULL AND OLD.FIXED_DATE IS NULL) BEGIN
    :NEW.FIXED_DATE := SYSDATE;
END;

/
ALTER TRIGGER "APP_ATEN_DANOS"."TRG_SET_FIXED_DATE" ENABLE;

CREATE UNIQUE INDEX "APP_ATEN_DANOS"."ATTENTION_ORDER_PK" ON "APP_ATEN_DANOS"."ATTENTION_ORDER" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN APP_ATEN_DANOS.ATTENTION_ORDER.ORDER_DESCRIPTION IS 'Description of the damage from the Order.';
COMMENT ON COLUMN APP_ATEN_DANOS.ATTENTION_ORDER.REPORT_DATE IS 'Date when the damage was reported by the customer.';
COMMENT ON COLUMN APP_ATEN_DANOS.ATTENTION_ORDER.CUSTOMER_ID IS 'Reference to the customer who reported the damage.';
COMMENT ON COLUMN APP_ATEN_DANOS.ATTENTION_ORDER.DAMAGE_ID IS 'Reference to the type of damage reported';
COMMENT ON COLUMN APP_ATEN_DANOS.ATTENTION_ORDER.TECHNICIAN_ID IS 'Reference to the technician assigned to fix the damage. Can be NULL if no technician is assigned yet.';
COMMENT ON COLUMN APP_ATEN_DANOS.ATTENTION_ORDER.DURATION IS 'Estimated duration to fix the damage.';
COMMENT ON COLUMN APP_ATEN_DANOS.ATTENTION_ORDER.FIXED_DATE IS 'Date when the damage was fixed.';
COMMENT ON COLUMN APP_ATEN_DANOS.ATTENTION_ORDER.ORDER_ID IS 'Unique identifier for each attention order.';

CREATE TABLE "APP_ATEN_DANOS"."CREW" 
   (	"CREW_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(80) NOT NULL ENABLE, 
	"ZONE" VARCHAR2(50) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "APP_ATEN_DANOS"."CREW_PK" ON "APP_ATEN_DANOS"."CREW" ("CREW_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
ALTER TABLE "APP_ATEN_DANOS"."CREW" ADD CONSTRAINT "CREW_PK" PRIMARY KEY ("CREW_ID")
  USING INDEX "APP_ATEN_DANOS"."CREW_PK"  ENABLE;

CREATE UNIQUE INDEX "APP_ATEN_DANOS"."CREW_PK" ON "APP_ATEN_DANOS"."CREW" ("CREW_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "APP_ATEN_DANOS"."CUSTOMER" 
   (	"CUSTOMER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAME" VARCHAR2(80) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(100) NOT NULL ENABLE, 
	"DISTRICT" VARCHAR2(50) NOT NULL ENABLE, 
	"TYPE" NUMBER(1,0) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6), 
	 CHECK ("TYPE" BETWEEN 1 AND 5) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "APP_ATEN_DANOS"."CUSTOMER_PK" ON "APP_ATEN_DANOS"."CUSTOMER" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
ALTER TABLE "APP_ATEN_DANOS"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX "APP_ATEN_DANOS"."CUSTOMER_PK"  ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "APP_ATEN_DANOS"."TRG_UPDATE_CUSTOMER" 
BEFORE UPDATE
ON CUSTOMER
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/
ALTER TRIGGER "APP_ATEN_DANOS"."TRG_UPDATE_CUSTOMER" ENABLE;

CREATE UNIQUE INDEX "APP_ATEN_DANOS"."CUSTOMER_PK" ON "APP_ATEN_DANOS"."CUSTOMER" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "APP_ATEN_DANOS"."DAMAGE" 
   (	"DAMAGE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200) NOT NULL ENABLE, 
	"PRIORITY" NUMBER(1,0) NOT NULL ENABLE, 
	"ESTIMATED_DURATION" INTERVAL DAY (2) TO SECOND (6), 
	 CHECK ("PRIORITY" BETWEEN 1 AND 5) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "APP_ATEN_DANOS"."DAMAGE_PK" ON "APP_ATEN_DANOS"."DAMAGE" ("DAMAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
ALTER TABLE "APP_ATEN_DANOS"."DAMAGE" ADD CONSTRAINT "DAMAGE_PK" PRIMARY KEY ("DAMAGE_ID")
  USING INDEX "APP_ATEN_DANOS"."DAMAGE_PK"  ENABLE;

CREATE UNIQUE INDEX "APP_ATEN_DANOS"."DAMAGE_PK" ON "APP_ATEN_DANOS"."DAMAGE" ("DAMAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "APP_ATEN_DANOS"."TECHNICIAN" 
   (	"TECHNICIAN_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"DOCUMENT" VARCHAR2(20) NOT NULL ENABLE, 
	"DOCUMENT_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"CREW_ID" NUMBER(10,0) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "APP_ATEN_DANOS"."TECHNICIAN_PK" ON "APP_ATEN_DANOS"."TECHNICIAN" ("TECHNICIAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
ALTER TABLE "APP_ATEN_DANOS"."TECHNICIAN" ADD CONSTRAINT "TECHNICIAN_PK" PRIMARY KEY ("TECHNICIAN_ID")
  USING INDEX "APP_ATEN_DANOS"."TECHNICIAN_PK"  ENABLE;

ALTER TABLE "APP_ATEN_DANOS"."TECHNICIAN" ADD CONSTRAINT "FK_TECHNICIAN_CREW" FOREIGN KEY ("CREW_ID")
	  REFERENCES "APP_ATEN_DANOS"."CREW" ("CREW_ID") ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "APP_ATEN_DANOS"."TECHNICIAN_BIR" 
BEFORE INSERT ON APP_ATEN_DANOS.TECHNICIAN
FOR EACH ROW
BEGIN
  IF :new.TECHNICIAN_ID IS NULL THEN
    SELECT technician_seq.NEXTVAL
    INTO   :new.TECHNICIAN_ID
    FROM   dual;
  END IF;
END;

/
ALTER TRIGGER "APP_ATEN_DANOS"."TECHNICIAN_BIR" ENABLE;

CREATE UNIQUE INDEX "APP_ATEN_DANOS"."TECHNICIAN_PK" ON "APP_ATEN_DANOS"."TECHNICIAN" ("TECHNICIAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "APP_ATEN_DANOS"."TECHNICIAN_SPECIALTY" 
   (	"TECHNICIAN_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DAMAGE_ID" NUMBER(10,0) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "APP_ATEN_DANOS"."TECHNICIAN_SPECIALTY" ADD CONSTRAINT "FK_TECHNICIAN_SPECIALTY_TECHNICIAN" FOREIGN KEY ("TECHNICIAN_ID")
	  REFERENCES "APP_ATEN_DANOS"."TECHNICIAN" ("TECHNICIAN_ID") ENABLE;
  ALTER TABLE "APP_ATEN_DANOS"."TECHNICIAN_SPECIALTY" ADD CONSTRAINT "FK_TECHNICIAN_SPECIALTY_DAMAGE" FOREIGN KEY ("DAMAGE_ID")
	  REFERENCES "APP_ATEN_DANOS"."DAMAGE" ("DAMAGE_ID") ENABLE;

COMMENT ON TABLE APP_ATEN_DANOS.TECHNICIAN_SPECIALTY IS 'CHILETEL Technician Specialties table';

CREATE SEQUENCE APP_ATEN_DANOS.ATTENTION_ORDER_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE APP_ATEN_DANOS."ISEQ$$_76181" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE APP_ATEN_DANOS."ISEQ$$_76185" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE APP_ATEN_DANOS.TECHNICIAN_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;